//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscalationMatrix.DBClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMatrixEntities : DbContext
    {
        public EMatrixEntities()
            : base("name=EMatrixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EM_Header> EM_Header { get; set; }
        public virtual DbSet<EM_history> EM_history { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
    }
}
