//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscalationMatrix.DBClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_history
    {
        public int EM_HistoryID { get; set; }
        public Nullable<int> EM_Header_ID { get; set; }
        public string Window { get; set; }
        public string NameOfAssociate { get; set; }
        public Nullable<int> ContactDetails { get; set; }
        public Nullable<int> Addedby { get; set; }
        public Nullable<System.DateTime> Addedon { get; set; }
        public Nullable<int> Updateby { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    
        public virtual EM_history EM_history1 { get; set; }
        public virtual EM_history EM_history2 { get; set; }
    }
}
