//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscalationMatrix.DBClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_Header
    {
        public int EMHeader { get; set; }
        public string ComplaintType { get; set; }
        public string ScopeofWork { get; set; }
        public Nullable<int> Addedby { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> Updateby { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
